from typing import Any

def setup_directories() -> None: ...
def make_folder(year: Any, month: Any, day: Any, hour: Any): ...
def assets_download(dic_start_params: Any, dic_end_params: Any) -> None: ...
def csv_folders(year: Any, month: Any, day: Any, hour: Any, root_dir: Any = ...): ...
def merge_csv(tmp_dir: Any, csv_dir: Any, categories: Any, csv_time: Any) -> None: ...
def flash_csv(file: Any, file_idx: Any, tmp_dir: Any, root_dir: Any) -> None: ...
def group_csv(file: Any, file_idx: Any, tmp_dir: Any, root_dir: Any) -> None: ...
def event_csv(assets_dir: Any, csv_dir: Any, root_dir: Any) -> None: ...
def create_csv(year: Any, month: Any, day: Any, hour: Any, categories: Any, root_dir: Any = ..., lat1: int = ..., lat2: int = ..., lon1: int = ..., lon2: int = ...) -> None: ...
def data_acces(dic_start_params: Any, dic_end_params: Any, categories: Any, dic_coordinates: Any = ...) -> None: ...
def csv_filter(csv_path: Any, csv_time: Any, categories: Any, lat1: int = ..., lat2: int = ..., lon1: int = ..., lon2: int = ...) -> None: ...
def in_square_maker(lat1: Any, lat2: Any, lon1: Any, lon2: Any): ...
def generate_map(dic_start_params: Any, dic_end_params: Any, radius: Any, center: Any, category: str = ...) -> None: ...
